# fly.toml app configuration file generated for klubi-si-api on 2024-10-31T22:38:39+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'klubi-si-api'
primary_region = 'ams'

[processes]
app = "bin/rails server"
worker = "bin/rails jobs:work"

[build]
  dockerfile = 'Dockerfile'

[http_service]
  processes = ['app']
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
